version: "3"
networks:
  trella-net:
    driver: bridge
services:
  trelladb:
    container_name: trelladb
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5430:5432
    networks:
      - trella-net
    env_file:
      - .env
  trella-be:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: trella-be
    restart: always
    ports:
      - 8088:8080
    networks:
      - trella-net
    env_file:
      - .env
    depends_on:
      - trelladb

